name: chest
description: Cultural Heritage Educational Semantic Tool is an application for teachers to transparently annotate points of interest and learning tasks as Linked Open Data and for their students to complete them.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  latlong: ^0.6.1
  flutter_map: ^2.2.0
  flutter_map_marker_cluster: ^0.5.4
  flutter_map_tile_caching: ^5.1.1
  geolocator: ^9.0.1
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  http: ^0.13.5
  mustache_template: ^2.0.0
  universal_io: ^2.0.4
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4
  email_validator: ^2.1.17
  url_launcher: ^6.1.5
  fwfh_url_launcher: ^0.6.1+3
  flutter_widget_from_html_core: ^0.8.5+3
  #flutter_launcher_icons: ^0.10.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "images/icon/chestIcon.png"
#   min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
